Repository linjmeyer/tilt-pitch, pull requests merged in 2021-04, with the labels that each got.

#28 Fixed yellow and pink uuids
  pitch/pitch.py
Labels: bug

#30 Add Taplist.io cloud provider.
  README.md
  pitch/configuration/pitch_config.py
  pitch/pitch.py
  pitch/providers/__init__.py
  pitch/providers/taplistio_custom_stream.py
Labels: documentation, enhancement

#29 Add support for InfluxDB 2
  README.md
  pitch/configuration/pitch_config.py
  pitch/pitch.py
  pitch/providers/__init__.py
  pitch/providers/influxdb2.py
  requirements.txt
Labels: enhancement
